name: Go Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ Build-and-Test-Actions ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Documentation
      run: |
            go get golang.org/x/tools/cmd/godoc
            godoc -http=:6060
